=== bengtmartensson/Girr/trunk/src/main/doc/girr-schema-doc/girr.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified">
    <!--targetNamespace='http://www.harctoolbox.org/girr' -->
    <!--xs:import namespace="http://www.w3.org/XML/1998/namespace"/-->
    <!--xs:import namespace="http://www.w3.org/1999/xhtml"/-->
    <!--xs:import namespace="http://www.harctoolbox.org/girr"/-->

    <xs:simpleType name="masterEnum">
        <xs:annotation>
            <xs:documentation>Determines whether the raw representation, the ccf or the parameters are the masters of the data.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="raw"/>
            <xs:enumeration value="ccf"/>
            <xs:enumeration value="parameters"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ccfHexType">
        <xs:annotation>
            <xs:documentation>Data type describing a four-digit hexadecimal number.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:hexBinary">
            <xs:length value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="between0and1">
        <xs:annotation>
            <xs:documentation>Number between 0 and 1.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:double">
            <xs:minExclusive value="0.0"/>
            <xs:maxExclusive value="1.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="remotes">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>This element models a set of remotes. It may act as a data base for a program or device.
                </xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element ref="adminData" minOccurs="0"/>
                <xs:element ref="remote" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="noNamespaceSchemaLocation" type="xs:anySimpleType" use="optional"/>
            <xs:attribute ref="girrVersion" use="required"/>
            <xs:attribute ref="title" use="optional"/>
        </xs:complexType>
        <xs:unique name="remoteNameUnique">
            <xs:selector xpath="remote"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:attribute name="title" type="xs:string">
        <xs:annotation>
            <xs:documentation>Textual title of the document.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="girrVersion" fixed="1.0" type="xs:string">
        <xs:annotation>
            <xs:documentation>Version of the Girr specification the document claims to follow.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="name" type="xs:string">
        <xs:annotation>
            <xs:documentation>Name that is used to identify the element.
                Should therefore be unique in the context.
                Even though arbitrary strings are allowed, C type strings,
                in the English language, are recommended.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="display-name" type="xs:string">
        <xs:annotation>
            <xs:documentation>Name of the command as being displayed to the user.
                Special characters and non-english languages are here appropriate.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="comment" type="xs:string">
        <xs:annotation>
            <xs:documentation>Textual comment.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="lang" type="xs:language">
        <xs:annotation>
            <xs:documentation>Language as defined in XML 1.0.</xs:documentation>
        </xs:annotation>
    </xs:attribute>

    <xs:attribute name="value" type="xs:nonNegativeInteger">
        <xs:annotation>
            <xs:documentation>Numerical value for a parameter. Nonnegative integer with base 10.</xs:documentation><!-- TODO: allow hex -->
        </xs:annotation>
    </xs:attribute>

    <xs:element name="adminData">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="creationData" minOccurs="0"/>
                <xs:element ref="versioningData" minOccurs="0"/>
                <xs:element ref="notes" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueLanguagesInNotesAdminData">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
    </xs:element>

    <xs:element name="creationData">
        <xs:annotation>
            <xs:documentation>Describes how, from what, and by whom the document was created.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="creatingUser" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of creating user</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="source" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Source of the information, for example, another document that was converted to the present one.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="creationDate" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Date of creation, or last modification.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="toolVersion" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Version of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool2" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of secondary creating tool, if applicable.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="tool2Version" type="xs:string" use="optional">
            <xs:annotation>
                    <xs:documentation>Version of creating tool.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="versioningData">
        <xs:annotation>
            <xs:documentation>Versioning data; semanics is still to be determined.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="notes">
        <xs:annotation>
            <xs:documentation>Textual notes.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:attribute ref="lang" default="en"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="remote">
        <xs:annotation>
            <xs:documentation>The element models an abstract remote, which is basically a collection of commands.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="adminData" minOccurs="0"/>
                <xs:element ref="notes" minOccurs="0" maxOccurs="unbounded"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="applicationData"/>
                    <xs:element ref="img"/>
                </xs:choice>
                <xs:element ref="commandSet" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="girrVersion" use="optional"/>
            <xs:attribute ref="comment" use="optional"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute name="manufacturer" type="xs:string"/>
            <xs:attribute name="model" type="xs:string"/>
            <xs:attribute name="deviceClass" type="xs:string"/>
            <xs:attribute name="remoteName" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Name of captured remote control as a component. Normally different from the name.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="title" use="optional"/>
        </xs:complexType>
        <xs:unique name="uniqueLangsInNotesInRemote">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
        <xs:unique name="uniqueNamesInCommands">
            <xs:selector xpath="commandSet/command"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueNamesInCommandSets">
            <xs:selector xpath="commandSet"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueApplicationsInApplicationData">
            <xs:selector xpath="applicationData"/>
            <xs:field xpath="@application"/>
        </xs:unique>
    </xs:element>

    <xs:element name="applicationData">
        <xs:annotation>
            <xs:documentation>Data, only relevant for a particular application or domain, can be embedded here.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="notes" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="appParameter" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="application" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Name of application or domain the application data is intended for.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
        <xs:unique name="uniqueNamesInAppParameter">
            <xs:selector xpath="appParameter"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="appParameter">
        <xs:complexType>
            <xs:attribute ref="value" use="required"/>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="parameter">
        <xs:complexType>
            <xs:attribute ref="value" use="required"/>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="commandSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="notes" minOccurs="0"/>
                <xs:element ref="parameters" minOccurs="0"/>
                <xs:element ref="command" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="display-name"/>
            <xs:attribute ref="name"/>
            <xs:attribute ref="comment"/>
        </xs:complexType>
        <xs:unique name="uniqueLangInNotesInCommandSet">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
    </xs:element>

    <xs:element name="parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="notes" minOccurs="0"/>
                <xs:element ref="parameter" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="protocol" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Protocol name as known to e.g. IrpMaster.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
        <xs:unique name="uniqueLangInNotesInParameters">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
        <xs:unique name="uniqueNamesInParameters">
            <xs:selector xpath="parameter"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="command">
        <xs:annotation>
            <xs:documentation>A command is essentially an IR signal with a name.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="notes" minOccurs="0"/>
                <xs:element ref="parameters" minOccurs="0"/>
                <xs:element ref="raw" minOccurs="0"/>
                <xs:element ref="ccf" minOccurs="0"/>
                <xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="F" type="xs:nonNegativeInteger">
                <xs:annotation>
                    <xs:documentation>Value of the F parameter for the current command in the current protocol (if applicable).</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="display-name" use="optional"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="comment"/>
            <!--xs:attribute name="application-id" type="xs:anySimpleType"/-->
            <xs:attribute name="master" type="masterEnum" use="optional" default="raw"/>
            <xs:attribute ref="title"/>
            <xs:attribute ref="girrVersion" use="optional"/>
        </xs:complexType>
        <xs:unique name="uniqueLangsInNotesInCommands">
            <xs:selector xpath="notes"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
    </xs:element>

    <xs:element name="raw">
        <xs:annotation>
            <xs:documentation>Models a raw IR signal, with into, repeat, and ending sequence (any of these may be empty).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:sequence>
                        <xs:element ref="intro"/>
                        <xs:element ref="repeat" minOccurs="0"/>
                    </xs:sequence>
                    <xs:element ref="repeat"/>
                </xs:choice>
                <xs:element ref="ending" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="frequency" type="xs:nonNegativeInteger">
                <xs:annotation>
                    <xs:documentation>Carrier frequency in Hz.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="dutyCycle" type="between0and1">
                <xs:annotation>
                    <xs:documentation>Duty cycle of modulation signal, between 0 and 1.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="rawsequence" mixed="true">
        <xs:annotation>
            <xs:documentation>Models a raw IR sequence, defined by its durations.
                This should be either a sequence of numbers, or alternating flash and gap elements.
                Unfortunately, this cannot be described in XML Schemas :-(.</xs:documentation>
        </xs:annotation>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="flash"/>
            <xs:element ref="gap"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="intro" type="rawsequence"/>
    <xs:element name="repeat" type="rawsequence"/>
    <xs:element name="ending" type="rawsequence"/>

    <xs:element name="ccf">
        <xs:simpleType>
            <xs:list itemType="ccfHexType"/>
        </xs:simpleType>
    </xs:element>

    <xs:element name="format">
        <xs:complexType mixed="true">
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="flash" type="xs:nonNegativeInteger"/>
    <xs:element name="gap" type="xs:nonNegativeInteger"/>

    <xs:element name="img">
        <xs:complexType>
            <xs:attribute ref="name"/>
            <xs:attribute name="src" type="xs:anyURI">
                <xs:annotation>
                    <xs:documentation>URL to image</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== bengtmartensson/Girr/trunk/test/testfiles/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE remotes SYSTEM "girr.dtd">
<remotes
         xmlns="http://www.harctoolbox.org/girr"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:html="http://www.w3.org/1999/xhtml">
         <!--xsi:schemaLocation="http://www.harctoolbox.org/girr http://www.harctoolbox.org/schemas/girr.xsd"-->
    <notes><html:p>This is <html:b>quite</html:b> nice.</html:p>
    </notes>
    <remote version="1.0" id="r1" name="tester" comment="just a test">
        <notes/>
        <application-data application="jp1">
            <notes/>
            <parameter name="setup-code" value="1234"/>
            <button-map>
                <button name="play" display-name="Play" unshifted="cmd1" shifted="stop" metashifted="record"/>
            </button-map>
        </application-data>
        <command-set id="c1" comment="">
            <notes/>
            <parameters id="p1" protocol="nec1">
                <parameter name="D" value="0"/>
            </parameters>
            <command id="cmd1" name="play" display-name="Play |>" comment="">
                <notes/>
                <parameters>
                    <parameter name="F" value="0"/>
                </parameters>
                <raw frequency="38400">
                    <intro>+9024 -4512 +564 -564 +564 -564 +564 -564 +564 -564 +564 <!-- no ids on sequences -->
                        -564 +564 -564 +564 -564 +564 -564 +564 -1692 +564 -1692 +564 -1692 +564 -1692
                        +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -564 +564 -564 +564 -564 +564
                        -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -1692 +564 -1692 +564 -1692
                        +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -39756
                    </intro>
                    <repeat>+9024 -2256 +564 -96156</repeat>
                </raw>
                <ccf>0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C</ccf>
                <format name="uei-learned">00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 11 12 22 22 22 21 11 11 11 12 22 22 22 23 82 45</format>
            </command>
            <command F="1" name="stop">
                <raw>
                    <intro>
                        <flash>9024</flash>
                        <gap>4512</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>39756</gap>
                    </intro>
                    <repeat>
                        <flash>9024</flash>
                        <gap>2256</gap>
                        <flash>564</flash>
                        <gap>96156</gap>
                    </repeat>
                </raw>
                <ccf>0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C</ccf>
                <format name="uei-learned">00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 11 12 22 22 22 22 11 11 11 11 22 22 22 23 82 45</format>
            </command>
            <command F="2" name="record">
                <raw>
                    <intro>
                        <flash>9024</flash>
                        <gap>4512</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>564</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>1692</gap>
                        <flash>564</flash>
                        <gap>39756</gap>
                    </intro>
                    <repeat>
                        <flash>9024</flash>
                        <gap>2256</gap>
                        <flash>564</flash>
                        <gap>96156</gap>
                    </repeat>
                </raw>
                <ccf>0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C</ccf>
